-- cú pháp:
--SELECT COLUMN_NAME
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'table_name';


-- ví dụ:
SELECT	COLUMN_NAME as N'Tên cột'
FROM	INFORMATION_SCHEMA.COLUMNS
WHERE	TABLE_NAME = 'PA_SAL_IMPORT_BACKDATE';